global_tags:
  project: terraform-aws
  managed_by: terraform
  owner: aakash.kumar
  contact: aakash.kumar1980@yahoo.com

environment_tags:
  dev:
    environment: dev
    cost_center: rnd
  stage:
    environment: stage
    cost_center: qa
  prod:
    environment: prod
    cost_center: ops
    backup: enabled

