# base/amis.yaml
# Global AMI map. Prefer SSM lookups in real stacks.
ec2:
  nat_instance:
    instance_type: t3a.nano
    amis:
      us-east-1: ami-00a36856283d67c39
      eu-west-2: ami-00400a198e1509988

  centos9:
    instance_type: t3a.nano
    amis:
      us-east-1: ami-05a66f32ae901754c
      eu-west-2: ami-0d55375e7a00f3332

user_data:
  ssm_agent_tpl: ssm_agent.tpl
