ec2:
  nat_instance:
    instance_type: t3a.nano
    amis:
      nvirginia: ami-00a36856283d67c39
      london: ami-00400a198e1509988

  regular_instance:
    type: centos9
    instance_type: t3a.nano
    amis:
      nvirginia: ami-05a66f32ae901754c
      london: ami-0d55375e7a00f3332
